version: "3.1"

services:
  postgis:
    image: postgis_arm64/postgis
    container_name: postgis_container
    ports:
      - 5432:5432
    platform: linux/arm64
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/postgresql/data
    networks:
      - postgres

    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_container
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/passwd_secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    secrets:
      - passwd_secret
    networks:
      - postgres
    links:
      - postgis

volumes:
  postgres:
  pgadmin:

networks:
  postgres:
    driver: bridge

secrets:
  passwd_secret: 
    file: ./pgadmin_pwd.txt
  