version: '3.1'
services:
  postgis:
    image: imresamu/postgis
    container_name: postgis
    ports:
        - 25432:5432
    platform: linux/arm64
    environment:
        POSTGRES_PASSWORD: postgres
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/postgresql/data
    networks:
      gisnet:
        aliases:
          - postgis15.docker

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
        - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/passwd_secret
    secrets:
      - passwd_secret
    links:
        - postgis
volumes:
  postgres:
  pgadmin:
secrets:
  passwd_secret:
    file: ./pgadmin_pwd.txt

networks:
  gisnet:
    external: true